"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
sys.path.append('src')
import pymasvis.analyze as analyze

from setuptools import setup

APPNAME = 'PyMasVis'
APP = ['src/PyMasVis.py']
DATA_FILES = []
#OPTIONS = {'argv_emulation': True}
OPTIONS = {
	'compressed': True,
	'optimize': 2,
	'strip': True,
	'plist': {
		'CFBundleGetInfoString': 'PyMasVis, Python Mastering Visualization',
		'CFBundleIdentifier': 'org.joakimfors.PyMasVis',
		'CFBundleVersion': analyze.VERSION,
		'CFBundleShortVersionString': analyze.VERSION,
		'NSHumanReadableCopyright': 'Joakim Fors'
	}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
